# Generated by Django 5.2.16 on 2026-07-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('total_distance', models.FloatField(blank=True, help_text='Total distance in miles', null=True)),
                ('total_duration', models.FloatField(blank=True, help_text='Total duration in hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('stop_type', models.CharField(choices=[('CURRENT', 'Current Location'), ('PICKUP', 'Pickup Location'), ('DROPOFF', 'Dropoff Location'), ('REST_BREAK', 'Rest Break'), ('SLEEPER', 'Sleeper Berth')], default='REST_BREAK', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('sequence_order', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='planner.trip')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_hours', models.FloatField(default=0.0)),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_hours', models.FloatField(default=0.0)),
                ('remaining_cycle_hours', models.FloatField(default=70.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='planner.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
