import React, { useState } from 'react';
import FMCSADailyLogSheet from './FMCSADailyLogSheet';

/**
 * DailyLogPlaceholder component managing multi-day FMCSA Driver Daily Log sheets.
 * Provides paginated sheet navigation controls (Next, Previous, Sheet X of Y indicators, and Day tabs).
 *
 * @param {Object} props
 * @param {Array} props.logs - Array of daily log objects generated by backend
 * @param {Array} props.dailyLogs - Alternative prop alias for daily logs array
 */
const DailyLogPlaceholder = ({ logs, dailyLogs }) => {
  const [selectedDayIdx, setSelectedDayIdx] = useState(0);

  const actualLogs = dailyLogs || logs || [];
  const hasLogs = Array.isArray(actualLogs) && actualLogs.length > 0;
  const totalSheets = hasLogs ? actualLogs.length : 0;
  const currentLog = hasLogs ? actualLogs[selectedDayIdx] || actualLogs[0] : null;

  const handlePrev = () => {
    if (selectedDayIdx > 0) {
      setSelectedDayIdx((prev) => prev - 1);
    }
  };

  const handleNext = () => {
    if (selectedDayIdx < totalSheets - 1) {
      setSelectedDayIdx((prev) => prev + 1);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-2xl backdrop-blur-md">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-800">
          <div>
            <h3 className="text-xl font-bold text-slate-100 flex items-center space-x-2">
              <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              <span>FMCSA Driver Daily Log Sheets</span>
            </h3>
            <p className="text-xs text-slate-400 mt-1">Official 24-hour driver log sheets with vector duty status graph</p>
          </div>

          <span className={`text-xs font-mono px-3 py-1.5 rounded-lg border self-start md:self-auto ${hasLogs ? 'bg-emerald-950 text-emerald-300 border-emerald-800' : 'bg-slate-800 text-slate-500 border-slate-700'}`}>
            {hasLogs ? `${totalSheets} Log Sheet(s) Generated` : 'Awaiting Trip Plan'}
          </span>
        </div>

        {!hasLogs ? (
          <div className="py-12 text-center bg-slate-950/60 rounded-xl border border-slate-800/80 mt-6">
            <svg className="w-10 h-10 text-slate-600 mx-auto mb-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <p className="text-sm font-semibold text-slate-300">No Driver Daily Logs Available</p>
            <p className="text-xs text-slate-500 mt-1">Submit the trip planner form to generate official FMCSA daily log sheets.</p>
          </div>
        ) : (
          <div className="mt-6 space-y-6">
            {/* Paginated Navigation Bar */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-950/90 p-3 rounded-xl border border-slate-800">
              {/* Previous Button */}
              <button
                type="button"
                onClick={handlePrev}
                disabled={selectedDayIdx === 0}
                className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition flex items-center space-x-1.5 ${
                  selectedDayIdx === 0
                    ? 'bg-slate-900 text-slate-600 border border-slate-800 cursor-not-allowed'
                    : 'bg-slate-800 hover:bg-indigo-600 text-slate-200 hover:text-white border border-slate-700 shadow-md'
                }`}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                <span>Previous Sheet</span>
              </button>

              {/* Page Indicator Badge */}
              <div className="text-center font-mono text-xs">
                <span className="text-slate-400">Sheet </span>
                <span className="font-bold text-indigo-400">{selectedDayIdx + 1}</span>
                <span className="text-slate-400"> of </span>
                <span className="font-bold text-slate-200">{totalSheets}</span>
                <span className="text-slate-500 font-semibold ml-2">
                  (Day #{currentLog?.day_number} — {currentLog?.date})
                </span>
              </div>

              {/* Next Button */}
              <button
                type="button"
                onClick={handleNext}
                disabled={selectedDayIdx >= totalSheets - 1}
                className={`px-4 py-2 rounded-xl text-xs font-mono font-bold transition flex items-center space-x-1.5 ${
                  selectedDayIdx >= totalSheets - 1
                    ? 'bg-slate-900 text-slate-600 border border-slate-800 cursor-not-allowed'
                    : 'bg-slate-800 hover:bg-indigo-600 text-slate-200 hover:text-white border border-slate-700 shadow-md'
                }`}
              >
                <span>Next Sheet</span>
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>

            {/* Quick Day Tab Shortcuts */}
            {totalSheets > 1 && (
              <div className="flex items-center space-x-2 overflow-x-auto pb-1">
                <span className="text-xs font-mono uppercase text-slate-400 mr-1 shrink-0">Quick Jump:</span>
                {actualLogs.map((logItem, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => setSelectedDayIdx(idx)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-semibold transition shrink-0 ${
                      selectedDayIdx === idx
                        ? 'bg-indigo-950 text-indigo-300 border border-indigo-700'
                        : 'bg-slate-900/60 text-slate-400 hover:text-slate-200 border border-slate-800'
                    }`}
                  >
                    Day {logItem.day_number || idx + 1}
                  </button>
                ))}
              </div>
            )}

            {/* Active FMCSA Paper Log Sheet */}
            {currentLog && <FMCSADailyLogSheet log={currentLog} />}
          </div>
        )}
      </div>
    </div>
  );
};

export default DailyLogPlaceholder;
