import apiClient from './api';
import { fallbackPlanTrip, generateDailyLogs } from './fallbackPlanner';

export const tripService = {
  /**
   * Send trip planning parameters to backend API.
   * If backend is unreachable or throws a Network Error (e.g. Vercel deployment without backend),
   * seamlessly falls back to the client-side OpenStreetMap + FMCSA HOS engine.
   *
   * IMPORTANT: After receiving trip data from ANY source (backend or fallback),
   * daily_logs are ALWAYS regenerated client-side from the timeline to ensure
   * the FMCSA Driver Daily Log Sheets stay synchronized with the
   * "Merged HOS & Operational Timeline" (single source of truth).
   *
   * @param {Object} tripData - { currentLocation, pickupLocation, dropoffLocation, currentCycleUsed, locationDetails }
   * @returns {Promise<Object>} API response data object
   */
  planTrip: async (tripData) => {
    try {
      const payload = {
        current_location: tripData.currentLocation,
        pickup_location: tripData.pickupLocation,
        dropoff_location: tripData.dropoffLocation,
        current_cycle_used: parseFloat(tripData.currentCycleUsed || 0),
      };

      const response = await apiClient.post('/trip/plan', payload);
      const data = response.data?.data || response.data;

      // ── Always regenerate daily_logs from the timeline ──────────
      // The backend may return daily_logs generated by an older version
      // of DailyLogGenerator. To guarantee the FMCSA graph matches the
      // Merged HOS & Operational Timeline, we rebuild daily_logs here
      // using the frontend's generateDailyLogs (single source of truth).
      if (data && data.timeline && data.timeline.length > 0) {
        data.daily_logs = generateDailyLogs(
          data.timeline,
          parseFloat(tripData.currentCycleUsed || 0)
        );
      }

      return response.data;
    } catch (error) {
      console.warn('Backend API connection failed, executing client-side route planner fallback:', error);

      // If it's a validation error response from backend, throw it
      if (error.response && error.response.status === 400) {
        const resData = error.response.data;
        if (resData.data && typeof resData.data === 'object') {
          const firstKey = Object.keys(resData.data)[0];
          const errList = resData.data[firstKey];
          const message = Array.isArray(errList) ? errList[0] : String(errList);
          throw new Error(`${firstKey.replace('_', ' ')}: ${message}`);
        }
        if (resData.message) {
          throw new Error(resData.message);
        }
      }

      // Execute seamless client-side fallback planner for Network Errors or 5xx server issues
      try {
        const fallbackResult = await fallbackPlanTrip(tripData);
        return fallbackResult;
      } catch (fallbackErr) {
        console.error('Fallback Planner Error:', fallbackErr);
        throw new Error(error.message || 'Server connection error. Please try again.');
      }
    }
  },
};

export default tripService;
